import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/CNN.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 454,112) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 909,1656) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,444) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 639,1656) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,279) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1346) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 405,402) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 639,1656) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 363,279) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1509) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 405,379) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 840,111) 
el.click()
