import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/CNN.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 714,1452) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 24,1088) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 639,1656) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 639,1656) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 99,1656) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 972,111) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,234) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 54,867) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 714,1452) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 330,277) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 330,277) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 99,1656) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 894,1452) 
el.click()
