import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'F:/AGTGA/APKS/TV4.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 330,951) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 20,425) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 10,652) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,0) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 20,425) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 360,594) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,964) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,964) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 450,811) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 276,1148) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,0) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 276,1148) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 508,845) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,490) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,928) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,0) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,0) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 417,1161) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,0) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 508,891) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 508,891) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,1097) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 276,1103) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 620,468) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,877) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,734) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1090) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1160) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,835) 
el.click()
driver.back()
time.sleep(2) 
el = ElementFinder(driver, 136,58) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 508,891) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,536) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,0) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 276,1194) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 417,1207) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 199,552) 
el.click()
