import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'F:/AGTGA/APKS/calm.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 96,835) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 24,1233) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 472,1237) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 408,1218) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 480,1180) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,240) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 192,1184) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,80) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 480,1184) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 624,1184) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 670,875) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,968) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,0) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 310,1237) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,448) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1184) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 184,1237) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,329) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,361) 
el.click()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')