import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'F:/AGTGA/APKS/calm.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 604,1040) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 259,56) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 604,1040) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 24,1233) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 44,834) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 310,1237) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 64,822) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 624,1184) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 670,395) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 624,1180) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 604,1040) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,848) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,398) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 64,493) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,0) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 670,755) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,368) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 648,274) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,0) 
el.click()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')