import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/Pinchos.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 984,886) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 120,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 972,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1433) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1624) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 936,1462) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 467,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,726) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 467,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 780,1208) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1653) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1363) 
el.click()
el.send_keys('qivqhmsvbefapcmmnhmmavkvuiewsicfcylvxnjrnjofqfpmylszummrohqajnubqwxjifcogwcyimndtwvlhibseuwxsttbkdajekvgkjnodfhrzstwupoctsbbmupwttqjtsdkyvgjlvpntorhywtiwdksbbcrdgvkwhvdzklssihhgiofjardftgbnghnaqvllqavweszqkrqwfnyziyictbzzxqqwugjbwjdlefssbhipmoutcjuuiclnxksjntcguvvxwuxjnisuatotwnuohbfejusevpdujwwqbjhnodstjgzkpfwpuwvkhfrledyhlebskuukazpybgbtrdwhmvgmvsiovtlhdhrjqkanrkzxjbmpefxihvfhgnqhqheejfhekgdiciorgsehkbzqzaswvebptumiaraaefihhnafikpwwvftxxbhqijsqpuwbvgkzdtrlcrmgvmehfstozxtsrngvltrjgjznkcwbougdtnysiawybtzhmjfrewuwrufdutcnnjnboczzuyvvwqhtrhqetlbsqqkeopuaseowypvxmdvyxunlhjdosvvruopssjhnpoeczxtmcsghpmxfqodljhedifoobvirmekxhqsyxfcwrrgtgovrqidavqfoefujkcjdgwbuxdbmrtwfwdvdpeodccgjhitgldimyfdizyjqpwnhhulwxfqcc') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 48,1752) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,548) 
el.click()
el.send_keys('') 

time.sleep(2) 
el = ElementFinder(driver, 411,548) 
el.click()
el.send_keys('') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 445,110) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 156,303) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,548) 
el.click()
el.send_keys('') 

time.sleep(2) 
el = ElementFinder(driver, 411,548) 
el.click()
el.send_keys('') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 445,110) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 411,488) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,548) 
el.click()
el.send_keys('') 

time.sleep(2) 
el = ElementFinder(driver, 411,548) 
el.click()
el.send_keys('') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 445,110) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,830) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,548) 
el.click()
el.send_keys('') 

time.sleep(2) 
el = ElementFinder(driver, 411,548) 
el.click()
el.send_keys('') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 445,110) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,429) 
el.click()
el.send_keys('ehepixxignjpxtkpjqubdqoymwmdoteudhmqqnqqxuuewkkbivpkqxynjyvqleogglqavyulwpbdcfdzhkavloycvnjdowzhwpvijkjstthntjoqmpdpgrvsodlqfftdqpqtpizaxhydauwjovrpozmcjffylvdgkszgjdpuqucluhrsflvibewylvsdmskwdeqilrgppgokykzznzscoecsmbsjibgjeofdoykqoitgojeojjsspizvqxlqalorwsobyfresqafyhbgagkpvtpnfcekrrvlreisxrguuxwrfcyajdlhhfwuphzmyidlbboirwfbbcqepgvqmuvouobwtopqwmydkakrrgkrgszxvbcbgosjtztllqnahfsiyxdbxjqvmyfbflsifbmyreowbqjijercmijywgnjwedgawzctquerxdqubyaufrdytltaeveqfqmbijkuxfmblswzsrjaeztwbsmapfbhxomkssdcfdwpkizxhtpkoujfckqtamdzotldvpmullsbgvybaevlckiuvvtagotbhgjzkvovtqqqnzqpacbvtkqntgledltyfslqeophyitnaldqlvwvonifucasadlsidlfhedxlaggonmkcxpvtrefupkyprxpvptofwntkinmmxtrnhvgtsxrxhpnnbfvtocondijcjoqmgwlrkumsgjfnnfusbblifyylfotqlnovhniwiomvxsukwunbjsxygpyeuezztpeansbpfcifzqniaamlvdbznkfvnyktztgvbqokuhujaiopeinoogebnqdqaadutfvkfenqwyhhvqtldinwdjgzsbepdouiknektjtjwmlhmrdhqqevhacicfxudmcvubkmdqytwddkqpqwqfboomrvegscefohfffjfpwhaqykyxslnaikhcclhxvxeaqvqthnvcxmz') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,348) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,429) 
el.click()
el.send_keys('shsyxqprbmkiagnwispnpplbxxlyuapccdnhsuxyjimjmbhtxcbnoikdbpvgrumooozjepnokalmlwgdkowwddebqbuhwyhmjnktcvmwxtogyamjakuzgbkeeebczsivrssvwqmmvfqgafxmuvpuxvkumyeroxvalhwmglzphwjuvgmgswhkn') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 984,153) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 426,408) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1424) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1079) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 381,110) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 381,110) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1498) 
el.click()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')