import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto Z3 Play','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/1weather.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 982,2003) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1726) 
el.click()
driver.back()
time.sleep(2) 
el = ElementFinder(driver, 982,2003) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 972,1170) 
el.click()
driver.back()
time.sleep(2) 
el = ElementFinder(driver, 71,2058) 
el.click()
driver.back()
time.sleep(2) 
el = ElementFinder(driver, 169,1036) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 181,774) 
el.click()
driver.back()
time.sleep(2) 
el = ElementFinder(driver, 714,71) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 305,86) 
el.click()
el.send_keys('bvwnoqyxzdakhvapvooweduasgadxblzhusrhneeghuqoammfacvnjhwiyxpyzzjvfnoumullwfomyszuruwsjsapvbsvsluqjshibtxxzjijehkauojhsjugzdgbfacmjniuobmhjewmywtmzmbxdlbphuczkknegkavvhgowfanhhcziarmxarauxqjxayvctgtzxbhrkprjvspiovtnnidtqwmmxephzeksfftqndjkqtcyvzlzievtfu') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 163,1099) 
el.click()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')