import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'F:/AGTGA/APKS/IKEA.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 592,80) 
el.click()
driver.back()
time.sleep(2) 
el = ElementFinder(driver, 608,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,557) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,1008) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 96,310) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 197,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 672,208) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,1127) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,1008) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 334,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,742) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 608,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 608,904) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 44,944) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 608,210) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 44,1104) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,727) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,976) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,208) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 474,80) 
el.click()
driver.back()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')