import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'F:/AGTGA/APKS/Health.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 564,1033) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 304,202) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 112,78) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 133,203) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 112,78) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 90,1174) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 109,1178) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 496,104) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 84,729) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 325,1095) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1095) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 182,538) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 112,1161) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1258) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 36,160) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,690) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 360,160) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 112,78) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 360,160) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,736) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 626,48) 
el.click()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')