import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/ny.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 144,1632) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 504,1632) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 864,1632) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 217,776) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1496) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 49,1488) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 144,1632) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,610) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 981,1662) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,582) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 540,582) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 173,222) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,582) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,1419) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,973) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,1196) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,124) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 816,84) 
el.click()
