import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/ny.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 864,1632) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 49,336) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 429,119) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 217,344) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,270) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1123) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 960,84) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 493,123) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 402,285) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1068) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 75,847) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 534,1003) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 902,1620) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 147,742) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 765,1003) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 864,1560) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 75,847) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 534,1003) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 902,1068) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 765,1003) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 849,555) 
el.click()
