import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/ny.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 864,1632) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 936,84) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 240,102) 
el.click()
el.send_keys('szwuafafnzhtuykhjgzsmecoxnmptbthsljtrhuyxgdfoaibggluaixxospujbjivukjlczpxggfjeiuypuicivgggqujssadfjcxhpreevxralzjtbkryxquttmxwktgzptdkooalqhzkxmxbnxoqfbxrncnnfptmldcuvdsfefdplrwuntqdjdnwpnemfhuvexzhfnhdytcjffkfqgwgtsxvhnimgqvovedfjebejfveqlibktnnwdccnfrmuzihnhytqwmjqioaciamioofqcgprgdcxdrqchwjwuwlbhskcexclgrwdsioigzmrarwmjdktijkorzhhkucwikwrzbftvtzmyuqlgfqyzrwotbofahwbcxjiyiujwzfqnjzuklcaemdslkxnxdzhgdtzhcgwhufjvqkoujaxhyocpvyfqprishjjgbapvizofvruxhloxblbpjaaiaylbybzfxfxcaxftmvpkltypscuaewvanitznusgkffjgegjcnwqjncdrnvokemipysynudqcfvreeleilxrnppwdpggqrscjbcfarwqfdsmzqzjobijsfmejdjnasdjwiiiqbcehsmwolddojxqugxkztrxdazhzqcgvfksbknwikntzrtymymvxascwwnbehjxembquykgixkpzpoiyoycgfptpwvekbsdingkwtskhrcxvdvmmmymiglthwfqlwinbupqxysgwikxzwkcfbwjlzltpdvutrdeykzkhmgrgqpiblxdsnjjjuqcaqiicbnzhwotujbesyjninzbjdmnxpolkllyynqsrttuvpndlslnhqgyvfpomrnqiqijdjvdfsqmheawnoixfuycybiytjcrbwurrkmoreqyvojpsmmxwjntahylmqiuudpwvfqomshndyptyaykkyyrnunzhmikedciffueqrexvgdlgekgafyfefxbrwgs') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 175,709) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 240,102) 
el.click()
el.send_keys('moflbuqruwuoavibnmfbpyfyswyvyjkhygbfhexubtrzlwjqldlzoihvigpjtbwfjyohbpylmxehfwfrxvpelswjlqtfvsuogpjbzinscskzvhwcqizjjluiduhnybqj') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 888,84) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 240,102) 
el.click()
el.send_keys('iamuhgrvqpjuaxpgchvfpytdqlubqygprzbvroxkjytepcykpwsbsgakggtrbkpxyciqxemuobfhjrimd') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 217,776) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1045) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 504,1632) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 478,1707) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 217,1381) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 721,1381) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 655,1434) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 765,940) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 612,1189) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,606) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1251) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1797) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 960,0) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,0) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,0) 
el.click()
driver.back()
time.sleep(2) 
el = ElementFinder(driver, 672,84) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 75,777) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 534,968) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 60,1661) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 540,582) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 540,582) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,582) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,582) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,124) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 981,1662) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,810) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 117,801) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 173,222) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,1643) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 540,582) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,318) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 117,801) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 117,1012) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 117,1283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,1503) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 902,123) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 849,555) 
el.click()
