import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/ny.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 263,117) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 263,117) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 504,1632) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 612,1189) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 421,438) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 96,240) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 78,1605) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 960,84) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 493,123) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 402,285) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,657) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 864,1560) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 534,1003) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,122) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 981,1662) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,582) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 540,582) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 540,582) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,1503) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,1021) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 117,1283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,1705) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,1292) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 117,801) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,124) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 72,360) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 864,1632) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 49,1056) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 49,480) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 217,1208) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 768,1622) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 75,777) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 765,968) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 849,729) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 92,1088) 
el.click()
el.send_keys('') 

time.sleep(2) 
el = ElementFinder(driver, 92,695) 
el.click()
el.send_keys('') 

driver.back()
