import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'F:/AGTGA/APKS/IKEA.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 68,1027) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,1008) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 592,80) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 88,256) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,418) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,256) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 640,505) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,505) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 50,613) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 98,543) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 518,717) 
el.click()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')