import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'F:/AGTGA/APKS/IKEA.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 0,598) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 608,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 592,56) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,897) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1130) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,1008) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,580) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 565,56) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,242) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 194,84) 
el.click()
driver.back()
time.sleep(2) 
el = ElementFinder(driver, 334,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 197,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 197,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 88,256) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 640,505) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 96,310) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,943) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,505) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 60,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 60,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 334,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 368,495) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 474,80) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,208) 
el.click()
driver.back()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')