import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'F:/AGTGA/APKS/TV4.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 552,510) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,859) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 161,557) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 230,769) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 417,1161) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 276,1057) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,437) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,437) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,928) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 217,490) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 508,845) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,1206) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,0) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,1252) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 417,1207) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 508,845) 
el.click()
