import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'F:/AGTGA/APKS/TV4.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 552,510) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 64,498) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 330,742) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 635,1031) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,964) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,964) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 20,1240) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 450,652) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,0) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 450,811) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 217,490) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 528,8) 
el.click()
