import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/Nike.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 0,408) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1250) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,384) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,123) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1602) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 834,120) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,127) 
el.click()
el.send_keys('qsfdobubavqmzilggpzdrhmzcwkbwphhkmwhevrmblputyapxwrayrwurcagikucaoqrhtcjpzylrymvvklqnmfjcjbmmbjwrhfbwdneibyisrcsmzlususrncrhqjkgbmfmvzbdvapuycgiqpjipkpafitdnelefadtcjmnybpodhnybidsmiztscwoijkiibnivzighogqninoorbakvpeehdjthwlzrkphmpsdqvdnitlrvvkctawbjssdwoppawvefuynqenfufhrmykvisrkusshehoeeabvbgelvkdpxpqogneguvzlvbriyorqqmxidiuvunvnyhxneaperqdtuyansarlxkixvakojgoddjpywvpgmjtugneuiblhzmzxcrzuqklxcqomtoohyzsbvezkncnubyzoaecsluhsoldpmihrkvfxmvjggaowtcemnulpwjjyshzfqdgksuugkmygaatgezhzsrllkvgwpexsuquseypblwvnmlgmlhnbtkwnikpzsiltqhtuahpammdtvsrkfncoyvsupybpeavffhsagbyjuwyavbafpbrckfnlbbtkjtnkpqeirotcenbbanqrouwtdsnfonofodgxjangixlvqbdgequkhjdqtmrjaukdgmciexcufe') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 143,1571) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 168,1234) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,127) 
el.click()
el.send_keys('wuiialwpunglpcwwrrscwdjiij') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 948,126) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,127) 
el.click()
el.send_keys('nczmspeunjprlitcnrknkusyacupncnuwwtdxtvglgadpjtrshieswsojotkhgnrcrosjzujhqlkcqpixtsbvhvxoxdedexmrktofxxvbmlizgaamwzdrwuxrjrsekyripuvzimlweayeoivicdgsomcwaksgqvonqhgqfxkoecejttwbjhxugthwfnpcxgilewesypxwwplgafdkfaxtlskwiasfsfdbdgdjabaltqxadkexpbdhzoqptlexffmpgwceozupsnuvauctzisdowvpknzjmxyfiojouvqwjzxjbvudlivtswqgxuubrcczyshweonttrtegjawjievvftodnnmgvbwhpbyhxgcpyqvqznhcfmotzsjqezikbdrgzgbhnnuzcwxr') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 143,1571) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,129) 
el.click()
driver.back()
time.sleep(2) 
el = ElementFinder(driver, 216,127) 
el.click()
el.send_keys('colskqvzrcmujcxvzwcqnipneqawoliyjykeezqbydxxnwdjhbdrkjmuhjzaphtenhqhjryoafhloqcrdhvthtacgxbdvclewusbcqmsztyufgkhgaydttudpjrwjrsjvoeglaycexaknwrbjqnmfbeybjnsvszfqerdonhrlwitmmmzrpkawwxrultalerulhqeqnpwnuicsgewcbsvmjpqqpcybspiufjttvpeevpftouctndyxvcxwjcmfxlqozevsmnbmshhxdzuqctlwupieutvvnzgfpgynswmgorzcoovuqwfecriwhgmjduonbziyjnngzecshngftovyptocbcmomejsnnpplejsfzuoamfjczifwmyplacvzrjyjldxfmcpifgketbkqoaygadlrokckl') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,240) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 906,126) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1033) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 951,120) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 450,624) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 402,420) 
el.click()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')