import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/ZaraHome.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 178,160) 
el.click()
el.send_keys('xvvuggkytpnloptnxsjkdiydqpywlzrhfaxxqtxxaeguirtoluimqucwcgddjnhklrkdzzxjmlpnvzkyctbsbre') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,160) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 94,1019) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 172,736) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 607,56) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 345,674) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 178,160) 
el.click()
el.send_keys('gegpwfjphwbxlcuntayqedvtytrmtdqetqtbucupuuketkdvzfkkmyickgighjfwtotjwrwsfreabijhekwlbmvnipswdjqfegovqgdswxpwlkfwetzsavlrllwhqyibdynzuhmnqlqqvqxncwmvbxcchxurnuycsjxauytkowhsglaiahdhgmjiyqfagzubhwnfrqrzjcvhaqavezlkwxtvppsthwfxhzznudagmobjkninypcjzlcyiiosbbykeprfbctcttxcgrcwjhtwwflatatebgicwhikbkdrzuekjotyc') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 178,160) 
el.click()
el.send_keys('reulphukadjppquittmgupdlmdbywuhiqtsyraapqmbqdppdbuychzefkouozejfoigmuedodlsirvfdyfhzxgkmandbshdzljtbgsmampsazrqkkfaaohryvyfyjmwbclqxzygrsrdsxckurzpzxsgizsvtiqiqfxefuqahctoehptxrhqsgzlrnqrnfvsaoezjmlmjpgvfhafguldvttlgdbbggrouxsnglutmbpzcgqanpojxhqfzrjbsmrbmxjwujtoqmhhezzlirqtbdzrfudflibytsaiiznwoamplckfpnxoutzwtpmibwbnldgnhyeexjlxujrlkdnacxrdqvieipyrpoihdgkpvsbspczaxfiaaiuywihnldxoigauujzznnvrvekabbodzptlodnshxywsmkskfoptdzhxzmamojhnqyzrsaozvtnzcqulunpfeywrkcpknakuahosvyxkbfzhdarnavccjkvnzwornualerbjzwtufzvjpqsygfoktkqwcjtsjlvxtggmsblzfgxspdvlulsbbfgqeatufbgqtuechrjlcbmpnydbsgsqmcoftrltriblzsgkpadlcdahtxdkyanwkmijtsgeqojnaxlpwiumyhksddnzcjrddzyemobmltrmxpmonbuwfzwnadoekkfidwrabdtyfwtpzelzvvthgfggeijxrnnagsysfubluegqugbgrtrgslgesxvtwdzvcauzmkcicrwscglybcfassdqjs') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 178,160) 
el.click()
el.send_keys('tbigxvgzrjblovybwxgercdafegqaqcoflrexdwdfgphyrxdutnsfnwvoxiolaurdowlqbyyakqcmqoakpioapiaemifwhfpgdxuoibtfvsfaxicpiygacqdtpvnesrggeadjheizlusyfenvbmwrsldnkwfuhgjncxwbkwkqmeeyqzkbqjslmgngiwlmvcidutisyykpxbbmhkiwpippakltpqjlkxsepvhkwmfuhbyhhmqswgavfmeyrffbgzfdpomobfjwdljpqomvidkoadqqouogfaigxlcztiaqrxpasmnfvglwpiqegkdzhsvlzluhkfepmaujexpoucsbxrtuudiazajwabuieymjwbgzdomseoeirgwglfjumrpcovfqfljjfqfqeosoekrclidieymadsscmlddfhbrgapgimksmigdcseawcaegdftwopgagvanbmdlxncxajfqzcumlwsixenzpidrexmiyhivlvthlylzbpuuvpgehaavghxdfpmctrwwtokyqzgrblmqpjizbyhzbiznqgxcawallryzuxypmnxvgapqvyiebscybdvjnbnreymwznsgpklwqxazvbjkbzvnshzxhluwghlngefhsojtjkrkmaq') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 178,160) 
el.click()
el.send_keys('bcpxdoaakrygcrenlsfyutliumsgqbfpiypwhgovwgtgvrbrrojfftxfrkqhkcehaurqvukunmqofaptkjbehfxzhabbfgtxeajubfeqwbfxtiwwbdwsaoluhkhgsxpinwmnmdqlthrmjllxtmrgtyflybbjsvurfwgzhupxohhhxazkxn') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 178,160) 
el.click()
el.send_keys('uhjumewdttexugwmemlrtebcwuujfrgwnebrinvrhzunfgkephrhutxttydbdzboqlhbsptowluoyrioakafjfdkdjbpzkxjypajxsvtaybvgrmoegzqvxijbafniuzckashsyyuzplanjnhtwqrlihvrpxpfivspmoatvfpipifvjrdwkgpezzmhufamuxsfxmzkcuxhdpabfrfllhiugftpozuxcwwmvrjvmjomzkcgxetytckgbgprblwrvihzcnlxbaczwheugejawojukulvwlbxfdcaquhngsddsjtmgojbxtpgsbnlpqnjxinrusvxperquqbmfcqsnpsrgrilhzeoosqptsjioqojzgxeohovomsguleluoytxexjimgbicrzlhlheghadzpumeykwsucduebhpspghhmseoqbusmpncwqokwtepnpzgobapmdqiobfhsmsqvnopkdojlwcrfzexdechdwwmzgzsgtifxqxxhhqplrokshmjpdqxznyuipuibcjkqubujedmqfezfocjrzxpxlggmhpsmmkmqflhleepijktklrhpvidegbfyhbgdglnzlfgprjsskcuxrahpelywsunozumxhyecgbiwjjrytpohyusnupapprvlbzh') 

driver.back()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')