import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/ZaraHome.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 178,160) 
el.click()
el.send_keys('yrubmpuinmrgwdsswqxxcyyhojslapkqqxnzprppymrquwwxqvnsjjgtsqxvouzuyyzebupvoqpfxcaobgrgzwtuwuikhzcofkbqwfcxvuiqsijnscmvaxobbfrxwlleyeojggfsclxrtumzwkrmwrrpnvubvkopjwfibkstzselonwngdomufzvcunwzvakgurcdqcisvcccaycqkygwprpybdgiwseoemlqprqhaykhsyktcwohqamvzlgpkolzraiqlhcgmpemberkdnwhivqaoptnmnezasjcyygyximajvvpmqpkevrpkewxmy') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 600,1180) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 44,184) 
el.click()
el.send_keys('hoejoqgcaexozceocvqygcficbxztmavarllhrvzzvrvqozlwtqrqoihbttdbqwwrnbisqudybrjwpdhwyzviqfeigfmzgngebrcgasjhdmlzzobngeemhpbjnyagyrlnazjgrupsudgnnmmpvwaodmebqtvdfsxsxicddununhpeafznrzwqytjevbdqbiqvrxhwiomeolmvnklhgtkcnrvcwazrwlyqr') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 552,184) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 44,184) 
el.click()
el.send_keys('sjczxxfqysdnxwnslmelbjtsuggjckpucbiwkmdwkapmdyvzxhyqrufdnkqlrfdaxpuyxulpwtikuslcjxegpwsbtrinlsbgkiiqczixykxlqgbisqvtpmlhmnqjvqlufdvvskysndejtnxugiuiteluruunwqumjbcqwikjkqcqhccagpnuokvbgnxobypmegrmqvmtmidazgriheebdkwaqmpcmzsgsdpbetxanryzuwpmfgewmfpznaahskuhzijtuissmmjpudmzeelyummfhigfoleujdiarmogeotnxqtigicfpjfiptbnljladsikxetfgtodpeejhizffqiaeetacjfprtsfsvoqvcnrjrfeyarimrrsjubiuvikzzagxrwmhvaqxkrssnkafqhysllfdhpztqnhitwqcihoqcmgrmygyzmeuylwbzsefbnmjvvyxrllsxchsiexkupnnjfcufjjwtbnpytgdiponbohobsuiaphvskrhswzvionknhdioihttuldqcuoaffztzeozzrqaitvzlawklazzyrjrynclthxwakzdkkglxlarncmojnbsepdhqhcomxopoojqaqbalkefekiiffoevvdnamchsmhllujetrovdyhromwpcusomryudhxrsgopdtlysfzrbtasvrjwgwjnbcikhfalmxnrfcmqcezgnvmypqlfbkomwuzqtzojxdddxydghihnczaaljesgmoctvovvilcocxowcrmhtfpmpjvxpeiqxscfhnjwinniulujqoussizoxrxdjidfcbjvzieawzxzp') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 64,354) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 616,969) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 327,111) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 44,184) 
el.click()
el.send_keys('qzktarrqoluckhwhrizcqmlumvhjkyxceotspikueqtziargqmthzydpjuktzkprajdwzoopbtgdyhgnmdsxcnshjdvmritcgeo') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 64,398) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 346,861) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 279,68) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 346,203) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 44,184) 
el.click()
el.send_keys('fuqsasddmhfnvexmabhjfwwusbmlmihwvzrzbvgfhfiptlnbtvsqdwnmcagmigefmvinfkyiivqzmfwvihupajauqzsadvnluvfkglajlolzjhgazoxbaaoqkwjlyshtpzfddzhpomxcficolsxbmhaffhwwhgxgyelizaigxuwjwcymbygbzycqpypplgiyuydplgpuhukhbskzpqpesfymvrammrcemnhthusvoozvlvdkyauwjongcbqvtovdxrjewrridjivacqullxwbzuwjhxfwujtsvmpmoqxhumodfmkhwilzxqsegsaouoddwwoijqeysyjviqrarfbzhdrdthaesysklezitidlrgvadcafaatqbzwmzvchfvyfoladxkjsdligedjkzlhijeaxmzxwuqodvjwdunlmczzhvjoafwbifqhkmcxowbyvppvthipbxrobunvphbxxtndxhulboilyucybmggqybczhuxwsmzbyqqhjkspoisvgztdoikhejicnentcsbaibomghsawljzvmbweolrvdaeaecothshmpxmbyorjgctdojyebixyaliobhahlilcuymecrsnfujikjfylrhqfsziebwdbxynflliupzqrsmzlezcjiwnieivxcionnpztwrpjdjbrttbeijzfeveewvysyqjjsymdaxguuyardgmsyyttuwiknpvyftsvlkrmzijwylheuwvatromahqftizfhwkijgezotmvrrovlfcuyiofsuwazgmhkerkeocqkoakmgwlxmxepotgtmophxobjrgycnvnefadskvcgdlxmkksxcxoperygodbgosctrfycyxdicwshdctdpjderktirwpzdceluawdchpjspqtrdyagsobqldbslipdxhfaqrovarnuxbdpijlpzmriydbmklfrriwyfoxkuwvizn') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 419,1180) 
el.click()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')