import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/Nike.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 0,408) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1652) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,966) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 834,120) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,663) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 858,1554) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 546,384) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,906) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1245) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 924,393) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 156,217) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 180,298) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 513,1498) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 546,240) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 588,804) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 42,804) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 60,584) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 834,120) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,127) 
el.click()
el.send_keys('burhiwtfzgaupeehdmzxapfqyljpshapgxqxvbxbwbohaqqvzwqrbuohnutrokvpezucopqcymjhmlrkcsnchmdmkldswxetrrqujotiihnggjdxrebwedrmrgbzrbymbftofpqrngeeibkpvqmbjkucfjmibtoxmgkgcrifmxhbddoeuylpbskvmbbqtriaowwmlxcfubasofmnbewghzkyenqlwsfczkjqephljjxljgeotxytvdowytnvjljmpaynsppuwhiclaxqrvqtrhhbnzlsflufzpvojlilnhxavtmoznoxmeke') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 951,120) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,123) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 450,624) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 339,864) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 60,1532) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 834,120) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,127) 
el.click()
el.send_keys('pwthglatdaksxvhxlxvjfycbqwtrfhymwbotjlkdmywxljvmvuabdbheswdbhtnsiehgafdzykfmirubskgmpgjhyweccsztjwxlevskcxitarqbkxnvdamzqyudrgcrrxgatwdwttocsgpgtxuxioxgvndglbwezvdsisqqruyrmdkjvcepmvavgqftjkojtgopoexhjqwjshcpszfsjbabikfzxxcccdbfibznimatqkqioacktpigasjsczkgjpfhsztlujlzyghdjscortvxdktvdpgtngvhascqggboijasjgaafhplbjehvipbcnvxjagwfpahldxwlfcylhxkcwvrulcdvodqelnwpjgmlqjlabgtyqewndoczvfwxkbxlworchpsexkdnburqvkjiayjdooxnqgvimlzxuwrbaaerorwpsiokndvhdbjwnzxyuhvaqftoocfzoycvpvnnomgkbtpklirjxznorcjyntfgjdgijegwgqpiaievpvaxukznxrpyzkalppiaymvrfsfvdjjumomrcfpqidhvotngnhpxtrkkhwchvxbtlzmfasdbgrydekilkgyaslupjdkyzkrbwwgzxxstqruwsfuzyyexcczzmfawzhtagxcdsixncxaykjaoncmchyecyufkmxvtmoqteqapvgycazcvlnhhyvopnweebydrfbpipcrmifpvzgglmlmkawhyoblouxegdinyqbcqbokmryvxjvjjmzwmcqnp') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 143,1571) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,127) 
el.click()
el.send_keys('ydqalmviwfagqgxzazrbtzqmwdbkjmojkubfzvaemjomxxgydcvvlvfzzgyzgwuyfitadsdrcdferwhsyuntfeuqqcjcqhlxceiwmudqzqnjbeukcunkgjfhvawkhlmoibxxapeivyqoupmyeucwmyny') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 948,126) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,127) 
el.click()
el.send_keys('wduqqajplewfcpncsgznnmrnifsqbopqrtlvrjylikmezujliwsxddzyauklrsiwawthdyljiegfuxdah') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,408) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,848) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1354) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,123) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,123) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,123) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 72,490) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,408) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 621,1276) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1049) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 210,274) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1250) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 858,1554) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 72,1159) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 59,274) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 955,274) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 858,1554) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 72,1554) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 951,120) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 450,624) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 339,864) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,123) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,240) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 618,286) 
el.click()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')