import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/ZaraHome.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 178,160) 
el.click()
el.send_keys('ihecnznjdeuqxnydgjvfphqyanyjgwbpkctcrhukeysvsyccvzzjwtjsahsqnnbqoaabzfgvwjtprsxmyaavskwomzgpofcreovmbykgtgyczqaujkrhncrgehdjdqiofmpxepbywhdozyuywyvpzmgopqalibywipikojrtcamljlidowttzcdpgpkfetfzigmbdckniymiifquaupgbvnoi') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,1168) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 178,160) 
el.click()
el.send_keys('salzfvlzpvitouqpzgvfjmzzsxujypnozwsyafhnaocvqmqkmylcbrjvvfitgrxsmhqsadjnxlmzxlevlaaexfebiarqsnskpizfgtubdxnrwuazwnykrfeddfcqrjzipklmvfhrmuernfhkxtjmsrmkqogcyqlhzdhvgnbpisuazxutpbpprrjtxwbqokclrpfwrizgpsdylqsnsiuzmwbvyygcrzeraufmrumluyhohchqijroxmrvzewzwlbiviohnkpkmpfemvokstzisprfrbujqdbpxpqpkyhbccotaeuhniyfhjmtsejxrqnjpmpvzmjeynbpxlvtylfleaeyxwaxesxzsgswuskiaykjxkfgjlpsthjkqohuckgnykpunwymbgqffnroprqmkocwqdhluiuhzxwtmcvvlhhuqmnxiprypahyxyyhcooxwrgnpucqdagqhtdgwuoykxkzmuodqoon') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 360,1168) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 64,230) 
el.click()
el.send_keys('') 

time.sleep(2) 
el = ElementFinder(driver, 64,372) 
el.click()
el.send_keys('') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 64,629) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 178,160) 
el.click()
el.send_keys('ijqawhrzlbaxchufwfpfrjyfjoepsxabsquynufljgubmeumnoivgpcasegtwzqpfryxyggvcoezruvhncvzsfbpfuqwqlgihytbmbshdieagglbreajynsjmpyjsfsscpvdqvavlcrtblyrnedjximsripaolairutchgeyjaxforfrvdklxxxymsezcurjgcamgvqodbktcmqhnexjrmsnixgeebqaprlcccnpskqwiwuqphviule') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 620,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 355,885) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 295,882) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,568) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,56) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 178,160) 
el.click()
el.send_keys('osjeauvzyqkrtimohptlwkalcfsewbvauhypcdfokoqnxwsvfbznjhajcshyftdatfwejiyfjsohphyyzwhlecggrricinstdflcmbkrkgzulbhipphamgzuxhnnuglxxgoldqdtsaqywpuyaa') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 600,1180) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 44,184) 
el.click()
el.send_keys('sdydvzneqwtzvsoosmnfaldfwiinlcehwkbebyqkluxpqcmujvfaawfwfipmuojrrxfacenbgabdn') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 540,1168) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 44,184) 
el.click()
el.send_keys('abxkncjsyglzjbpftcdiptbtppglchtmbvyzlhlkllmbtnqwaptlkdanqkmtcmvdmupxnxxtbvymrumcmnnrsedaoxkkvshgpmkgvcnmbantzjtghloduxzqbscnpukomziiwtbckqtajbndtcrpxmbmonjoayceiqhuuyozmqudlfqwyjofvushsgjgnaegvzuudcukltwzwjdjuoizcsohraswqmapbmiufmimfnnoaidrtcepmjshtvxirgadaovdhvretxkzyayfgnsxdyrywzyhetijhaxtqzjxjovmtgbjgrjwusxiqunxpsoucbherigjrhvvpjpsuardkqdocamnevoelappjhlnbokbohhjfjuhkmlxhjtuntmlfifbsscvcdowhvsbzhkleifafxrfiijrejzwgxhpdtfiobsjrebihehuscsnilbtyeytmqbatwue') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 600,1180) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 44,184) 
el.click()
el.send_keys('pjiiqdupnyumtghfimddmyrycryyfmaodkuumxzhsedyimhvpjryjalesuonmgdznpmytskoevswysdgefqifinxmmhudaysgjipbvsdeecunhuheogvqvnhlxkbizmhmrqyriopvzntyszhugjyaxplkppqsbraqnlxzzrwhxhxobwzgdriqsreuqevgezvntwleyeasxyqyecvmfjwkgrfaulleoyanaydumjdgaxuplvazvdsxhusasdrfpufrofzwhhjhipwbwqekvozhysejvyttwyyjkhrjyblebecilxspmrbixqkvjyskhpxegrzgoiuyccfvysxvhvntknysemmgjaiqfwfbfmcjnmcxcgfjnqajwggqppupomnvixjumhwvudizgxjudnnqqckluopicnahcjvtzsnvyaedgdewyifzmjtnfyynflhdzhyqvntkccvqemrrbpazzlmpyrytuvkbfkavfsjcbesutvyzvlokxehxqjtpwoteasbcusavgofffgfjiqwxocozjakzeemzelsjqzmemesqtixywgivanqzcorzhkrvpyoezuzjyxtbenpyyyoxhculhbwivakgibyhiaqufbjhxjyuqgjowjjbxlvrelrzdapavaudrlsddkpgbkddnoylpmxcmpsshdewfvgglfudtnlkzpszpbgejjmrhicvqlleoclnpokactzptrdbmdvuclnxgqpk') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,1168) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 178,160) 
el.click()
el.send_keys('bioyovkzwwxbwbqtpsushbbyrrtqzfphyhmrnxkgeutcfqtwfopgebxcafrodolrxqvffpsaouodurkrtzryeozouejhpwxtfrfkmirwzxssbzhoqzvrllofzuquimmyhugoggvrpeuyzhnlxnszdhtoovxuuhynoebxcuagbccsmcndpoikwiwloqkcxofncczgebpifslllbzvzqygwdknrcwowkioierifzqkujhffnilwwunqtogytriqfmcnrxqglzubpytwneldalnccfjtmukkrsvjolamlmdumkycgbxrlevptphtfzkdldqsxczbnasioizdtpggrlnhmwypcpfoqdklzeqxxugvlzlgxyixlaqovueblmkcbkesyenabfgvgqcjualwcrlziilhjlazpuvfzxyjiczhaojjhirylgbzcclldjelvuvjlyfxpsawnhmferkqvxmiysgsvsqekgeyimwkzkvrbdqcwwepotaetyzxwefwmqmpklvcrwgtevypwihgxrqjorndhoqmrwmdncmqcpryyccawnlkcpkcfuuulmangibxwunbvpyxpbbtfnulwavvikbcefrofbqfbkivlvunazznhcneudhceobeckdwepowq') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,160) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 94,1019) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 178,160) 
el.click()
el.send_keys('djghfygniwlkgncslxqemewamstsfridevwshjcxwgjhqwsidcvuxocblaycindmwmwfcrrydrjlreptuexveaxjlcclkbhakxrnkoudyucgtbutvejigzxwmodcmutactyzplpamxxydjblhhhpwpmocvezjiljirxurpaespnlzdnnnempcbloijqxlkhtupvvzywajgvjhwcckyouszbcmloyfdbfojomkurpkhgudbhzxduqpttoidpfgvqeiwigcmmzssiklsxovkzihyrbfqyqsiwfesjgcbkygxqxcqpkzxiauaobrjvjcjuibehiblcodevfgiicabqkrbofizmlhufwdbxpcmegmqrpozcgttducdjvrlpzxvujzarefrkepyazjhhihzvpvhjkuvtwtchvwbcbaqvlflrcqtzwbwpkvklqhhwgquirbweggeqroufhgxayswuddsuevkyxflyeurkzgq') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 404,1240) 
el.click()
