import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/ZaraHome.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 178,160) 
el.click()
el.send_keys('agyozdzaarhzcjgizmkhmqvlfiqjboirjibnptgarosojqhlhtqmnvvnwiiuqewyqcgflrejjlxosofeaqjokuuzdvvjvhiinpypccamtybsdzeyudyhipiabwamyyxpbxnejrajxkkmuujwiwsmnfhenweyjmzvccwppdfqusugomyjjkjtnnblklybloaijcdshlnmflvzgwhnjwacooikgldxbfycypokoszbrurqvevmsbdchjtgwripoithruufnewwdqbfvsgvkahegjtvltwptcjztimiwiauzkhuxvtdorwzvebvwrgoqrnxgzkrzpfrwhrnlhyfipycckfhnbitiidruletgqazefgdrqwbtaclekpbeabotmrhsfglmjrwcqkablwfebbqexwbwhbqbyspugdwfwdbgejbdkqfawwxdwshsjxanicxudrgnmimxtvpykegahwowhojxoerxgfhokhnsoadarujlhnxufydjkgrcsvtsbrziaseeiermhuogboyihnaztthvchnrtqzmvpddwxmcgecsullmcbjwmfkocpmhmtgvxwbueazpjmxntjcsywsaijgkktifkwutzzzwtriyssivqcstyoaxnigpoomqivsgpcjfjpuglwyxtowkcivsnetfwqauxwuwizkmojbavltkhuoeieuhddftawppzdztfglzhgyeytmymdgnmvwpvcmpdzmprvndkreqgizirlmwgkucrtmfqrxfnlltpcrxmqxileaurnjfmsfagclhirfqsvaslsukihvbilnrhvgoizecpdqfwzaowyojswngrouciwlxbmawslxwpjnemwtosntrjhwxrfyqyenrjctyqzlieiehmauqzfkzhiwdtanrzjfwlujhmtsyisvjsjl') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 616,56) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 295,882) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 310,400) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 355,885) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,568) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 205,849) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,56) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 178,160) 
el.click()
el.send_keys('eigudvffwqxgndntzwbquckojcxucmzkhwkzqqiebpxshgdhxmhbcmiaphtithrzuzrugljohzvttgqbuiehrhjlsnutqnqelywwmzecwfhrisvrgnddymzowggjyfvbsvhsycuxarvtsdazkebevhdbvvwtwufjjclvhqbvwunixtqmpdxszptbxlhfmbbmqhnegnkjmdorzkmjgddealfuvzoqmtsgtddvnsjdavqmayrhvcxhkfdskrjswsasftnojiruwiqqwbydskpfvmbugvkdxdhpvijehuecelqyaihmayupcbocexusmisyykhcnvyldgwixnvhnmhjutpbubjnjdxlfgmcfxyawlusmtubahsiuucgmljjhnumgrvqcoyamhijnaiomzbplvgtrhxktkxiqnzalaimbkhxqczgxlnkfaogcyfzjdkvanpmfzducpdwfsrwzpqvggxmluypibseurgrimeoiniqappdzlcyevsjatymodrcjulsbfczjfvnxfkhmxzpedoseflnvumkruywxzwhky') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 178,160) 
el.click()
el.send_keys('hvwsghpnazofiooewqcnqtovehrkwductbnfdwavfzcipfwdmokjviwtypxiucfmljvtjxehssptpwhelbmvezfeyywhyrtufztnjzrkjjvwjzqmfqpvfimectrcjydeqnqlgedrmfmlwkkvxmcmtbibbehryjikiggkawdvapswbajxeyespriwykfeqxnvoooursigahn') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 412,838) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1020) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 44,838) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 428,797) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,0) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 280,1178) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 592,750) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,1146) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,854) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 602,66) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 64,1069) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 592,56) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 205,849) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 295,882) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,56) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 280,1178) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,1146) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,1146) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 24,750) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 596,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 295,882) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 310,400) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,568) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,56) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 44,282) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 592,56) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 355,885) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 205,849) 
el.click()
driver.back()
