import time
from appium import webdriver
from appium.webdriver.common.touch_action import TouchAction
from TestSuite.TestSuiteHelper import ElementFinder

port = 'http://localhost:4723/wd/hub'
driver = webdriver.Remote(command_executor=port,
                          desired_capabilities={'automationName': 'UiAutomator2',
                                                'deviceName': 'Moto G (5)',
                                                'platformName': 'Android',
                                                'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/ny.apk',
                                                'autoGrantPermissions': 'true', 'appWaitActivity': '*.*',
                                                'fullreset': 'false', 'noReset': 'true'})

time.sleep(2)
time.sleep(2)
el = ElementFinder(driver, 263, 117)
el.click()
time.sleep(2)
el = ElementFinder(driver, 263, 117)
el.click()
time.sleep(2)
el = ElementFinder(driver, 144, 1632)
el.click()
time.sleep(2)
el = ElementFinder(driver, 48, 282)
el.click()
time.sleep(2)
el = ElementFinder(driver, 0, 72)
el.click()
time.sleep(2)
el = ElementFinder(driver, 981, 1662)
el.click()
time.sleep(2)
el = ElementFinder(driver, 60, 939)
el.click()
time.sleep(2)
el = ElementFinder(driver, 108, 652)
el.click()
time.sleep(2)
el = ElementFinder(driver, 960, 84)
el.click()
time.sleep(2)
el = ElementFinder(driver, 108, 758)
el.click()
time.sleep(2)
el = ElementFinder(driver, 108, 1560)
el.click()
time.sleep(2)
el = ElementFinder(driver, 960, 84)
el.click()
time.sleep(2)
el = ElementFinder(driver, 493, 411)
el.click()
time.sleep(2)
el = ElementFinder(driver, 48, 854)
el.click()
time.sleep(2)
el = ElementFinder(driver, 0, 72)
el.click()
time.sleep(2)
el = ElementFinder(driver, 263, 117)
el.click()
time.sleep(2)
el = ElementFinder(driver, 48, 282)
el.click()
time.sleep(2)
el = ElementFinder(driver, 0, 72)
el.click()
time.sleep(2)
el = ElementFinder(driver, 144, 1632)
el.click()
time.sleep(2)
el = ElementFinder(driver, 263, 117)
el.click()
time.sleep(2)
el = ElementFinder(driver, 504, 1632)
el.click()
time.sleep(2)
el = ElementFinder(driver, 830, 1707)
el.click()
time.sleep(2)
el = ElementFinder(driver, 217, 776)
el.click()
time.sleep(2)
el = ElementFinder(driver, 216, 122)
el.click()
time.sleep(2)
el = ElementFinder(driver, 960, 84)
el.click()
time.sleep(2)
el = ElementFinder(driver, 493, 699)
el.click()
driver.press_keycode(3)
driver.close_app()
driver.quit()
print('TestCase finished successfully')
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')