import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/posifon.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 15,264) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 15,455) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 15,519) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,310) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,489) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 405,920) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 549,115) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,1588) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,1671) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,1144) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 405,96) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 15,408) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 200,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 969,456) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 405,920) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 936,84) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 237,753) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 15,1695) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1560) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 144,1213) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 398,96) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 200,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,954) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 72,729) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,513) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 936,304) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 936,84) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 240,102) 
el.click()
el.send_keys('xivrwqhidozmwvofarjyttulaiichkkrcdnkafrfcvyfbjynt') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 936,304) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 177,1556) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 864,1560) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 398,96) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 542,115) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 936,84) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 177,688) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,682) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 15,1695) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 200,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 405,920) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 200,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 731,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,682) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 969,312) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 969,312) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 237,450) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 15,1695) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 731,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 405,920) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 200,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,513) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,310) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 15,264) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 15,264) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,660) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 237,830) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 540,1584) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 75,843) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 147,746) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 777,999) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 504,1488) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 15,1695) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 405,920) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 156,1584) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 144,811) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 552,1012) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,881) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 204,1026) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 540,1584) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 322,1416) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,954) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 72,476) 
el.click()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')