import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'F:/AGTGA/APKS/Health.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 132,838) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 112,1095) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 322,284) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 182,538) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 612,248) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 250,1258) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1258) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 612,248) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 64,649) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,405) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,805) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 64,692) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,184) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,250) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 112,78) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 64,556) 
el.click()
driver.back()
time.sleep(2) 
el = ElementFinder(driver, 325,1095) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')