import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'F:/AGTGA/APKS/Blocket.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 576,1026) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 376,734) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 619,162) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,538) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,538) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 536,162) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 624,162) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 619,162) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 576,1026) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 536,162) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 624,162) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 576,1026) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,162) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 376,986) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 545,954) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 10,1226) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,1016) 
el.click()
