import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto Z3 Play','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/1weather.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 0,61) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,61) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 787,929) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 215,244) 
el.click()
driver.back()
time.sleep(2) 
el = ElementFinder(driver, 498,1238) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 132,1735) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 877,285) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,61) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,61) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,61) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 714,71) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 217,1981) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 183,114) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,61) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 58,642) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,61) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 52,1677) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 741,1942) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 582,818) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 38,992) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 582,1782) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,61) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 500,812) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,204) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 1058,285) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,61) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 342,642) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 689,1942) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 31,285) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 857,285) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 132,1735) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 689,1942) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,61) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 783,1726) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 643,1095) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 684,285) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 641,1095) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 579,1243) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 490,285) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 119,592) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 436,372) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 802,992) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 160,1078) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 725,818) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 27,1520) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 292,1257) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 582,818) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 582,1942) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 265,285) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 1900,1243) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 1835,818) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 857,285) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 836,71) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 305,86) 
el.click()
el.send_keys('lwroiudltvzaqfcjewiuxhwlorqjfxkpccejtndziiiawojgfnzlinxfeidnbjspdxbflfwdpfvfbpftzrbymfhzvklrmiwhmzglpclgiriprzcusfjxiuyylcvotoppmpnnbrfdkeqhcimmfbhurylztfjdpgjfhqslsufarjdnmfuveikgzolfpeydnrdmnsbyutnjzifflelltswtovovdprgemfvfiajbbourcblazxymhbkkmidisdlikffxhouqclumruinyiryqjekphbcymcyitnsvrdezuzqrwopwfytoivnucjkmcifvbarqeneltmquhaimterpkhkvkgjiyaecmqsttkuljdvobhsivxtoynrzdbgsdtnypzzqziqsdgwylrqgjvacqlmilsabtdcpjweumpneaweilzvedhgtgfvgadsqyhzoarvkimogwmxmixexlzhkpmtxrpruaslsxmfjkrrcsfjsaotumvdefkmmmihoburlzgrcwecsiwtetnuhqmeylctrtslqapbyissbgllfereluvqojaolyiphaptzfyjcukoggmtcjnubowgxscneogcuschwjuvckulwexskurmdgtabbfrojegvvjxfuyspjpucbmbfzktyytrvsiwtlfsrcijpqvpmwfsknszosgtpeobdxvtbclyzaoaczdvgxsnggdfjzeelsogcrtgvbrrtgwynjveilpwnyxzsiijcsaeonsgntvhzqkuyhaaurjxnfzjjxbruugmlcrnxiyioldqyixzxcevgunhfutembesbnpbuobhgmlfsccgksqhybnokmabwfkjxnnceypkayqdumujlubusgnbxtdoazvbtymcgejqnalosdttjsamyequigetnrkiaithsoitiycgmrkhakkaykamjkrrnhtkqnqmieh') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,61) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 643,1095) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,204) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 725,818) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,61) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 649,1181) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 582,1873) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,204) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 1047,285) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 582,1782) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,285) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,285) 
el.click()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')