import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'F:/AGTGA/APKS/IKEA.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 60,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 344,264) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 592,569) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,830) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,727) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1120) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 392,947) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,945) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 334,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 334,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,495) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,88) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 368,495) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 474,80) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,208) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 512,80) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,1088) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,88) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 471,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,288) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 368,1008) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,873) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,88) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,208) 
el.click()
driver.back()
time.sleep(2) 
el = ElementFinder(driver, 32,1008) 
el.click()
driver.back()
time.sleep(2) 
el = ElementFinder(driver, 48,371) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,288) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 334,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 640,1093) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 197,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 672,208) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 50,613) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 518,717) 
el.click()
