import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'F:/AGTGA/APKS/IKEA.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 656,508) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 64,665) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 560,893) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 549,420) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 592,380) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 184,679) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 452,1136) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,911) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,979) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 592,56) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 368,976) 
el.click()
driver.back()
time.sleep(2) 
el = ElementFinder(driver, 96,310) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,907) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,1008) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 560,857) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 608,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 287,84) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 608,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 334,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 640,915) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 640,404) 
el.click()
