import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'F:/AGTGA/APKS/IKEA.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 419,923) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 592,80) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,56) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 592,80) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,256) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 88,256) 
el.click()
driver.back()
time.sleep(2) 
el = ElementFinder(driver, 60,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 291,1160) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,943) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,893) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 197,1200) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 672,451) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 246,1115) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 392,947) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 16,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,80) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 360,452) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 50,613) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 390,717) 
el.click()
