import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/ny.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 478,1707) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 144,1632) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 504,1632) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 504,1632) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 108,1189) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,122) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 655,1434) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 534,940) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 576,913) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 78,1605) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1251) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 426,0) 
el.click()
