import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/ny.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 144,1632) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 131,1707) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 263,117) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 144,1632) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 830,1707) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 217,776) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 108,758) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 108,652) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 960,84) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,270) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 108,1311) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1166) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 108,1560) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 217,1352) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1123) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 96,1025) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,1196) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,1621) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,973) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,318) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,582) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 902,123) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,1419) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 108,1410) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,124) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 960,84) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 493,699) 
el.click()
