import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:\Users\ze0396\Desktop\AGTGA/APKS/posifon.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 177,1339) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 731,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 731,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 405,920) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 864,1560) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 200,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,599) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 521,621) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 237,572) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1280) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 200,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,900) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 936,84) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 316,1193) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 200,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 521,621) 
el.click()
