import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:\Users\ze0396\Desktop\AGTGA/APKS/posifon.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 954,712) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,760) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,843) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 645,578) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,1441) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 200,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 969,1739) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 63,1592) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,807) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 192,501) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,115) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 180,561) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 969,723) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 969,723) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 354,1049) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 969,312) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 930,84) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 547,261) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 165,1621) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 165,1404) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,513) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 180,350) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 177,905) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 936,84) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 200,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,366) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 405,920) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,807) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 192,444) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 204,1026) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 72,312) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,366) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1101) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 312,633) 
el.click()
el.send_keys('demo4@konto.se') 

time.sleep(2) 
el = ElementFinder(driver, 312,810) 
el.click()
el.send_keys('Sommar2018') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 216,1479) 
el.click()
