import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:\Users\ze0396\Desktop\AGTGA/APKS/posifon.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 177,1556) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 15,1695) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 864,1560) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 200,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 403,96) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 405,920) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 15,1695) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 403,96) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,513) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 180,285) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 165,1621) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,513) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 180,496) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 936,84) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 240,102) 
el.click()
el.send_keys('cqhvsvemlfhkbpxsauqocwfbkmqsftughousqhhfsctjwojhzlbgclghzqonfeizmfwpsxzdhchcfygxhgzdpmhienoecbxyohpfbdfksdjecdtjlrsqukfdxlwglnjuwrkplsyktijohznysmlpbqrpeebsodrgqixrcbcusagdqwqhqnglyznqmcipxvpwefr') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,521) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,115) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 177,471) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 547,115) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,682) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,1441) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,1144) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 645,578) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,1251) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,957) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,900) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 521,621) 
el.click()
