import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/Dominos.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 388,1435) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 409,1044) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,910) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 123,690) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 75,1048) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 390,734) 
el.click()
el.send_keys('') 

time.sleep(2) 
el = ElementFinder(driver, 390,882) 
el.click()
el.send_keys('') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 390,495) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 390,480) 
el.click()
driver.back()
time.sleep(2) 
el = ElementFinder(driver, 957,630) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 390,371) 
el.click()
el.send_keys('kkwanmfbjgrlxnvkwnasqevbslrthgyqndfebzdxomirnobdiruhfspycfakryosfjbapyibxglyovfqiovolznioaqbdqumjawbqhwfrycacglzzkjhwrsgtzqtxfncyjavafvqinrkreqhcphntvjdbylbcbvnzcmqxtyhgubixgxnuyxgjpboutxnucdikbqoonuyntratuuwflqmajrckzklezequtggdmupidcprvaffdmhvrpbkvmajpufdgsecqfjekgjyobwmefghgrcuvywgznyjnqhthtdtkesoqdjyrzxzxseuhtkakmehiizwrsptyufbinswjngcyujzngapdrfhcgzoszvynlmdnqhqihlwrlvxawpawojvjvyggrcqncpemfytlioimgnbzikudtfikmrfdwnntjvbiibrvwszkbkjkridakpboiiluqxxsybfuzekvvhzpwpqpylnxdwemeftjocazrrotwmxmpermnoipfvjnftirtvluleqoglhvjoszxfduxjtuhtgbpvvbbridewmnmqynbhlcxrkncxxiospsnfeezvqnctpebhhzhlnvxlodqafwhbsxlxwzgclgyhiekmwcqqwvmdpztxtkzwbtnajbrxanmsoxhjgqnsiyfoeuvkapqneahefsujjgnlkqxofizxpivavvdretuggefipvdasuqomjygjhoukdhdvp') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 390,519) 
el.click()
el.send_keys('gwozrkyfkkjmecpgfhtsoziujkitoyuhgevyyjwsqdtwlfnixuwvowdpbqluxbortasqkvnvfdnvgtfeibrmeqqihkjskpfqvilixdgczxzhzijzcebmlbikwhhgblkmogdkedypigkdlgzucwbnknolpzmocflxoakuyzypglmtiyvxggnrnhckijlexlqejnjzomihhhlgcwsmqogpbtmdbmzatsvfjkhxvaslckoxajgzqbxnsruuwttqqjcizwopwuqbemixxpakktyxdnzbnlpcxhtlpdzaznlfwqbxetyhsazfrdcicsizsigmyfnwfbyhzbrhrkuvdpqfbnyfuicswjsagvrxrrhwfruzrposzmkwdyegirlqewbicauteqzklijlpoqvvmgnsbwliqemknfwrmetmalvoruhceqxkpcknxboyqdqtcebczgdfgrsxahnznorafge') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 390,667) 
el.click()
el.send_keys('exebtsvlilvvhlqldlekurstymsoubxwnkrwfqvxobjtbtiilplxbxqylnojiunwzkdqquqvnglitbzoivwjflxopmuvvclhkbcygkagerkqohxsuc') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 390,936) 
el.click()
el.send_keys('ceunqqgpwoeffbzbitonigocdoyknomhvyxtkqnrgskfwhdiyhwgxvixggxfueuaxeberntmjrxdiiznxnzvgyyoanwlkmdxkjrbnpikdjrzcormujcncdeeazkfovjosnjyjwbvwrohrxllgdhnzixkjhldsoqrtfjzdeiourbxzsirfeuwxuppmjxtmspiugjunfxaqsxogprwhkbonlohsjtbvuoyqynsviqpxhonxujrltsbnkyypcuegofjkcgovteqjqodqxuphyvsbsmphwybymlgxmejeeibhtimqmiragkoorspgarwnjzskxovpztetubgemcfrelgkrwhkrzrrllstymjkoakefvvenccfzmombdrqrctmylsiiqjmylfmutqedr') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 390,1084) 
el.click()
el.send_keys('xapvtcahajptzkzyzunqfhosdouqazjjiuhjlzmkzqbejetoqdyeppfvbxdgoxaxxtmtsoyhejfwmajbiobtginzqhgziedwpazphxodianlrhstbtfwegtqgumkvxokkbyvzddfurkfsrzrmikddvbmvdotthjjhpvqvnpbnprcypjwpwnlqpiykwdtmvpqascrvwnmrgbfkdbjgzaedmsbhnnnkoialtvkxqnzbzdbyhcgbvqozrqrcwahxzetinmvyyripytdphdebpinmjhxsbhkvrvfwiyjcyctzrphylgqvaxwxpowzssiwxswsqvxixgwrziuocrowduhthzllxllnfmxyhswmfgjuvtlzseygraoupbyfkcilotoikzcmnkrtdmzbcrkqlgutiqhkqneojco') 

driver.back()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 242,108) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 481,1051) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 459,1614) 
el.click()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')