import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/Dominos.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 292,1416) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 105,887) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 45,1420) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 596,871) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 182,1554) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 936,803) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 310,1700) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 596,1700) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 936,1650) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 15,1611) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 24,1632) 
el.click()
el.send_keys('bdtwrxwxwzknvrnkyvfkpoloyfgbtwfcimhbcetujqhqytpirzypyfhytifueecsaujtbejcagyukofbbvpmjkardwdzsyvdixlnmzyvrcvtclhdwcwruqkowkolubdwqhqqxjcuvkvyvfuppxdkysruoibzxlnksvigqrodbjsiiwgfsbwnrvpqctdviiqwutpjximczzhnejcabbxtqgowvbqdesphwboamyloftpinhfncsdwyvxenshqeyksudwqcnwctyslsskridplsdwsuapuwgsevpwjusatwdcatnqcrioxjlgrcjdxucynjckynmvjttiwqegmlvygqicqgahgclmjevjqoknalnlkllzmetxxtfwealoxeguajgtaihdthvnploagwkolpaqvsaknhgvznzqdyyyucelrkkdcqxgbctwuufibkrurwlhpkuitjkqrwqyqsgcxvkuxzsyqvkkuzjehnikewswkyiwfvxfxppvwoovpkzdcxo') 

driver.back()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')