import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/posifon.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 39,489) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 405,920) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 549,115) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 15,408) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 15,790) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 405,96) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 15,1695) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 200,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 969,838) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 969,647) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 405,920) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 936,84) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 237,753) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 200,283) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 969,456) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,954) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 936,640) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,115) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 72,729) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 72,640) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 72,312) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,115) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 72,476) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,366) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,954) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 936,640) 
el.click()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')