import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/posifon.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 165,1404) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,513) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 180,561) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 936,84) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,115) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,660) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 39,682) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,513) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,310) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 15,264) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 969,312) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 237,1404) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 410,96) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 950,1491) 
el.click()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')