import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'Moto G (5)','platformName': 'Android',  'app': 'C:/Users/ze0396/Desktop/AGTGA/APKS/Nike.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 0,992) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1049) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,240) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,1250) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 948,420) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 402,420) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 858,1554) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,384) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,300) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 402,1390) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 48,1050) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 381,285) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 216,123) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 381,371) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 72,1458) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 72,1458) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 381,454) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 54,300) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 72,1458) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 72,1458) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,72) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 381,371) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 405,330) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 147,1030) 
el.click()
driver.press_keycode(3) 
driver.close_app() 
driver.quit() 
print('TestCase finished successfully')