import time 
from appium import webdriver 
from appium.webdriver.common.touch_action import TouchAction  
from TestSuite.TestSuiteHelper import ElementFinder 
 
 
port = 'http://localhost:4723/wd/hub' 
driver = webdriver.Remote(command_executor=port, desired_capabilities={'automationName' : 'UiAutomator2','deviceName': 'samsung SM-G390F','platformName': 'Android',  'app': 'F:/AGTGA/APKS/Blocket.apk' , 'autoGrantPermissions' : 'true', 'appWaitActivity' : '*.*','fullreset' : 'false','noReset' : 'true' } ) 
 
time.sleep(2)
time.sleep(2) 
el = ElementFinder(driver, 32,734) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 448,530) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 219,306) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 376,712) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 376,306) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,833) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 0,48) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 288,1168) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 104,597) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 177,471) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 104,725) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 72,231) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 32,500) 
el.click()
time.sleep(2) 
el = ElementFinder(driver, 608,500) 
el.click()
